export const API_ROUTES = {
  BASE_URL: import.meta.env.VITE_API_URL || "http://localhost:4300",
  TIMEOUT: 30000,
  HEADERS: {
    "Content-Type": "application/json",
  },
};

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/api/auth/login",
    LOGIN_GOOGLE: "/api/auth/login/google",
    LOGIN_FACEBOOK: "/api/auth/login/facebook",
    CHECK_PHONE_EMAIL: "/api/auth/check-phone-email",
    SEND_OTP: "/api/auth/send-otp",
    SEND_OTP_VERIFY: "/api/auth/send-otp-verify",
    REGISTER: "/api/auth/register",
    FORGOT_PASSWORD: "/api/auth/forgot-password",
    VERIFY_OTP: "/api/auth/verify-otp",
    REFRESH_TOKEN: "/api/auth/refresh-token",
    UPDATE_PASSWORD: "/api/auth/update-password",
    CHANGE_PASSWORD: "/api/auth/change-password",
    ME: "/api/auth/me",
    LOGOUT: "/api/auth/logout",
  },

  EMPLOYEE: {
    PAGINATION: "/api/employee/pagination",
    FIND_BY_ID: "/api/employee/find-by-id",
    SELECTBOX: "/api/employee/selectbox",
    CREATE: "/api/employee/create",
    UPDATE: "/api/employee/update",
    DEACTIVATE: "/api/employee/deactivate",
    ACTIVATE: "/api/employee/activate",
    UPDATE_PROFILE: "/api/employee/update-profile",
    UPDATE_AVATAR: "/api/employee/update-avatar",
  },

  ROLE: {
    PAGINATION: "/api/role/pagination",
    FIND_BY_ID: "/api/role/find-by-id",
    SELECT_BOX: "/api/role/select-box",
    CREATE: "/api/role/create",
    UPDATE: "/api/role/update",
    DEACTIVATE: "/api/role/deactivate",
    ACTIVATE: "/api/role/activate",
  },

  PERMISSION: {
    PAGINATION: "/api/permission/pagination",
    FIND_BY_ID: "/api/permission/find-by-id",
    SELECT_BOX: "/api/permission/select-box",
    CREATE: "/api/permission/create",
    UPDATE: "/api/permission/update",
    DEACTIVATE: "/api/permission/deactivate",
    ACTIVATE: "/api/permission/activate",
    GET_PERMISSION_BY_ROLE: "/api/permission/get-permission-by-role",
    ASSIGN_TO_ROLE: "/api/permission/assign-to-role",
    REMOVE_FROM_ROLE: "/api/permission/remove-from-role",
    GET_PERMISSION_BY_USER: "/api/permission/get-permission-by-user",
    ASSIGN_TO_USER: "/api/permission/assign-to-user",
    REMOVE_FROM_USER: "/api/permission/remove-from-user",
    GET_MODULE_ACTIONS: "/api/permission/get-module-actions",
    SYNC_PERMISSIONS: "/api/permission/sync-permissions",
  },

  MEMBER: {
    PAGINATION: "/api/member/pagination",
    FIND_BY_ID: "/api/member/find-by-id",
    SELECTBOX: "/api/member/selectbox",
    CREATE: "/api/member/create",
    UPDATE: "/api/member/update",
    DEACTIVATE: "/api/member/deactivate",
    ACTIVATE: "/api/member/activate",
    UPDATE_PROFILE: "/api/member/update-profile",
    UPDATE_AVATAR: "/api/member/update-avatar",
  },

  NOTIFICATION: {
    PAGINATION: "/api/notify/pagination",
    FIND_BY_ID: "/api/notify/find-by-id",
    COUNT_UNREAD: "/api/notify/count-unread",
    MARK_AS_READ: "/api/notify/mark-as-read",
    MARK_ALL_READ: "/api/notify/mark-all-as-read",
    MARK_LIST_AS_READ: "/api/notify/mark-list-as-read",
    CREATE: "/api/notify/create",
    DELETE: "/api/notify/delete",
    CREATE_FOR_ADMIN: "/api/notify/create-for-admin",
    CREATE_FOR_USERS: "/api/notify/create-for-users",
    SEND_FROM_TEMPLATE: "/api/notify/send-from-template",
    CREATE_TEMPLATE: "/api/notify/create-template",
    UPDATE_TEMPLATE: "/api/notify/update-template",
    FIND_TEMPLATE_BY_ID: "/api/notify/find-template-by-id",
    FIND_TEMPLATE_BY_CODE: "/api/notify/find-template-by-code",
    PAGINATION_TEMPLATE: "/api/notify/pagination-template",
    DELETE_TEMPLATE: "/api/notify/delete-template",
    RENDER_TEMPLATE: "/api/notify/render-template",
  },

  EMAIL: {
    SEND_VERIFY_EMAIL: "/api/email/send-verify-email",
    SEND_FORGOT_PASSWORD_EMAIL: "/api/email/send-forgot-password-email",
    SEND_WELCOME_EMAIL: "/api/email/send-welcome-email",
    SEND_REMINDER_EMAIL: "/api/email/send-reminder-email",
    SEND_LATE_PAYMENT_EMAIL: "/api/email/send-late-payment-email",
    SEND_PAYMENT_CONFIRMATION_EMAIL: "/api/email/send-payment-confirmation-email",
    SEND_ACCEPT_EMAIL: "/api/email/send-accept-email",
    SEND_REJECT_EMAIL: "/api/email/send-reject-email",
    SEND_DISBURSEMENT_NOTIFICATION: "/api/email/send-disbursement-notification",
    SEND_DISBURSEMENT_CONFIRMATION: "/api/email/send-disbursement-confirmation",
    SEND_CYCLE_OPENING_EMAIL: "/api/email/send-cycle-opening-email",
    SEND_BULK: "/api/email/send-bulk",
  },

  FILE_ARCHIVAL: {
    CREATE: "/api/file-archival/create",
    CREATE_MANY: "/api/file-archival/create-many",
    FIND_BY_ID: "/api/file-archival/find-by-id",
    PAGINATION: "/api/file-archival/pagination",
    UPDATE: "/api/file-archival/update",
    REMOVE: "/api/file-archival/remove",
  },

  FUND: {
    PAGINATION: "/api/fund/pagination",
    FIND_BY_ID: "/api/fund/find-by-id",
    SELECTBOX: "/api/fund/selectbox",
    CREATE: "/api/fund/create",
    UPDATE: "/api/fund/update",
    DEACTIVATE: "/api/fund/deactivate",
    ACTIVATE: "/api/fund/activate",
    ADD_MEMBER: "/api/fund/add-member",
    REMOVE_MEMBER: "/api/fund/remove-member",
    LIST_MEMBERS: "/api/fund/list-members",
    CREATE_CYCLE: "/api/fund/create-cycle",
    UPDATE_CYCLE: "/api/fund/update-cycle",
    LIST_CYCLES: "/api/fund/list-cycles",
    CLOSE_CYCLE: "/api/fund/close-cycle",
  },

  FUND_CYCLE: {
    PAGINATION: "/api/fund-cycle/pagination",
    FIND_BY_ID: "/api/fund-cycle/find-by-id",
    SELECTBOX: "/api/fund-cycle/selectbox",
    CREATE: "/api/fund-cycle/create",
    UPDATE: "/api/fund-cycle/update",
    CLOSE: "/api/fund-cycle/close",
    DELETE: "/api/fund-cycle/delete",
  },

  CONTRIBUTION: {
    PAGINATION: "/api/contribution/pagination",
    FIND_BY_ID: "/api/contribution/find-by-id",
    SELECTBOX: "/api/contribution/selectbox",
    CREATE: "/api/contribution/create",
    UPDATE: "/api/contribution/update",
    CONFIRM: "/api/contribution/confirm",
    DELETE: "/api/contribution/delete",
    REMINDERS: "/api/contribution/reminders",
  },

  RECEIPT: {
    PAGINATION: "/api/receipt/pagination",
    FIND_BY_ID: "/api/receipt/find-by-id",
    CREATE: "/api/receipt/create",
    APPROVE: "/api/receipt/approve",
    REJECT: "/api/receipt/reject",
    APPROVALS: "/api/receipt/approvals",
  },

  DISBURSEMENT: {
    PAGINATION: "/api/disbursement/pagination",
    FIND_BY_ID: "/api/disbursement/find-by-id",
    CREATE: "/api/disbursement/create",
    CONFIRM: "/api/disbursement/confirm",
    CONFIRMATIONS: "/api/disbursement/confirmations",
  },

  TRANSACTION: {
    PAGINATION: "/api/transaction/pagination",
    BALANCE: "/api/transaction/balance",
  },

  SYSTEM_CONFIG: {
    PAGINATION: "/api/system-config/pagination",
    FIND_BY_ID: "/api/system-config/find-by-id",
    SELECTBOX: "/api/system-config/selectbox",
    CREATE: "/api/system-config/create",
    UPDATE: "/api/system-config/update",
  },

  LOGIN_LOG: {
    PAGINATION: "/api/login-log/pagination",
  },

  UPLOAD_FILE: {
    SINGLE: "/api/upload-file/upload-single",
    MULTI: "/api/upload-file/upload-multi",
    IMAGE: "/api/upload-file/upload-image",
    AUDIO: "/api/upload-file/upload-audio",
    DOCUMENT: "/api/upload-file/upload-document",
    CATBOX: "/api/upload-file/upload-catbox",
    CATBOX_URL: "/api/upload-file/upload-catbox-url",
  },

  ACTION_LOG: "/api/action-log/pagination",
};
