export const API_ROUTES = {
  BASE_URL: import.meta.env.VITE_API_BASE_URL || "http://localhost:4300",
  TIMEOUT: 30000,
  HEADERS: {
    "Content-Type": "application/json",
  },
};

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/api/admin/auth/login",
    LOGOUT: "/api/admin/auth/logout",
    REFRESH_TOKEN: "/api/admin/auth/refresh-token",
    ME: "/api/admin/auth/me",
    UPDATE_PASSWORD: "/api/admin/auth/update-password",
    CHANGE_PASSWORD: "/api/admin/auth/change-password",
  },

  ACTION_LOG: "/api/admin/action-log/pagination",

  NOTIFICATION: {
    PAGINATION: "/api/admin/notify/pagination",
    COUNT_UNREAD: "/api/admin/notify/find-count-notify-not-seen",
    MARK_ALL_READ: "/api/admin/notify/update-seen-all",
    MARK_READ_LIST: "/api/admin/notify/update-seen-list",
  },

  STUDENT: {
    PAGINATION: "/api/admin/student/pagination",
    CREATE: "/api/admin/student/create",
    UPDATE: "/api/admin/student/update",
    ACTIVATE: "/api/admin/student/activate",
    DEACTIVATE: "/api/admin/student/deactivate",
    DETAIL: "/api/admin/student/find-by-id",
    SELECT_BOX: "/api/admin/student/select-box",
    CHANGE_PASSWORD: "/api/admin/student/change-password",
    IMPORT_EXCEL: "/api/admin/student/import-excel",
    EXPORT_EXCEL: "/api/admin/student/export-excel",
  },

  TEACHER: {
    PAGINATION: "/api/admin/teacher/pagination",
    CREATE: "/api/admin/teacher/create",
    UPDATE: "/api/admin/teacher/update",
    ACTIVATE: "/api/admin/teacher/activate",
    DEACTIVATE: "/api/admin/teacher/deactivate",
    DETAIL: "/api/admin/teacher/find-by-id",
    SELECT_BOX: "/api/admin/teacher/select-box",
    CHANGE_PASSWORD: "/api/admin/teacher/change-password",
    IMPORT_EXCEL: "/api/admin/teacher/import-excel",
    EXPORT_EXCEL: "/api/admin/teacher/export-excel",
  },

  UPLOAD_FILE: {
    SINGLE: "/api/upload/upload-file/upload-single",
    MULTI: "/api/upload/upload-file/upload-multi",
  },

  ROLE: {
    PAGINATION: "/api/admin/role/pagination",
    CREATE: "/api/admin/role/create",
    UPDATE: "/api/admin/role/update",
    DEACTIVATE: "/api/admin/role/deactivate",
    ACTIVATE: "/api/admin/role/activate",
    DETAIL: "/api/admin/role/find-by-id",
    SELECT_BOX: "/api/admin/role/select-box",
  },

  PERMISSION: {
    PAGINATION: "/api/admin/permission/pagination",
    CREATE: "/api/admin/permission/create",
    UPDATE: "/api/admin/permission/update",
    DEACTIVATE: "/api/admin/permission/deactivate",
    ACTIVATE: "/api/admin/permission/activate",
    DETAIL: "/api/admin/permission/find-by-id",
    SELECT_BOX: "/api/admin/permission/select-box",
    ROLE_LIST: "/api/admin/permission/get-permission-by-role",
    ROLE_ASSIGN: "/api/admin/permission/assign-to-role",
    ROLE_REMOVE: "/api/admin/permission/remove-from-role",
    USER_LIST: "/api/admin/permission/get-permission-by-user",
    USER_ASSIGN: "/api/admin/permission/assign-to-user",
    USER_REMOVE: "/api/admin/permission/remove-from-user",
    GET_MODULE_ACTIONS: "/api/admin/permission/get-module-actions",
    SYNC_PERMISSIONS: "/api/admin/permission/sync-permissions",
  },

  BANNER: {
    PAGINATION: "/api/admin/banner/pagination",
    CREATE: "/api/admin/banner/create",
    UPDATE: "/api/admin/banner/update",
    DELETE: "/api/admin/banner/delete",
    DETAIL: "/api/admin/banner/find-by-id",
    SELECT_BOX: "/api/admin/banner/select-box",
    ACTIVATE: "/api/admin/banner/activate",
    DEACTIVATE: "/api/admin/banner/deactivate",
  },

  NEWS: {
    PAGINATION: "/api/admin/news/pagination",
    CREATE: "/api/admin/news/create",
    UPDATE: "/api/admin/news/update",
    DETAIL: "/api/admin/news/find-by-id",
    ACTIVATE: "/api/admin/news/activate",
    DEACTIVATE: "/api/admin/news/deactivate",
  },

  BLOG: {
    PAGINATION: "/api/admin/blog/pagination",
    SELECT_BOX: "/api/admin/blog/select-box",
    DETAIL: "/api/admin/blog/find-by-id",
    CREATE: "/api/admin/blog/create",
    UPDATE: "/api/admin/blog/update",
    DEACTIVATE: "/api/admin/blog/deactivate",
    ACTIVATE: "/api/admin/blog/activate",
    PAGINATION_BLOG_COMMENT: "/api/admin/blog/comments/pagination",
    FIND_BLOG_COMMENT_BY_ID: "/api/admin/blog/comments/find-by-id",
    APPROVE_BLOG_COMMENT: "/api/admin/blog/comments/approve",
    REJECT_BLOG_COMMENT: "/api/admin/blog/comments/reject",
    DELETE_BLOG_COMMENT: "/api/admin/blog/comments/delete",
    RESTORE_BLOG_COMMENT: "/api/admin/blog/comments/restore",
    PUBLISH_BLOG: "/api/admin/blog/publish",
    DRAFT_BLOG: "/api/admin/blog/draft",
    REJECT_BLOG: "/api/admin/blog/reject",
    ARCHIVE_BLOG: "/api/admin/blog/archive",
    UNARCHIVE_BLOG: "/api/admin/blog/unarchive",
    CHANGE_STATUS_BLOG: "/api/admin/blog/change-status",
  },

  COURSE: {
    PAGINATION: "/api/admin/course-manage/pagination",
    CREATE: "/api/admin/course-manage/create",
    UPDATE: "/api/admin/course-manage/update",
    DETAIL: "/api/admin/course-manage/find-by-id",
    ACTIVATE: "/api/admin/course-manage/activate",
    DEACTIVATE: "/api/admin/course-manage/deactivate",
    PUBLISH: "/api/admin/course-manage/publish",
    UNPUBLISH: "/api/admin/course-manage/unpublish",
    SELECT_BOX: "/api/admin/course-manage/select-box",
  },

  LESSON: {
    PAGINATION: "/api/admin/lesson-manage/pagination",
    CREATE: "/api/admin/lesson-manage/create",
    UPDATE: "/api/admin/lesson-manage/update",
    DETAIL: "/api/admin/lesson-manage/find-by-id",
    LIST_BY_COURSE: "/api/admin/lesson-manage/list-by-course",
    ACTIVATE: "/api/admin/lesson-manage/activate",
    DEACTIVATE: "/api/admin/lesson-manage/deactivate",
    ATTACHMENT_CREATE: "/api/admin/lesson-manage/attachment/create",
    ATTACHMENT_DELETE: "/api/admin/lesson-manage/attachment/delete",
  },

  TOPIC: {
    PAGINATION: "/api/admin/topic/pagination",
    CREATE: "/api/admin/topic/create",
    UPDATE: "/api/admin/topic/update",
    DETAIL: "/api/admin/topic/find-by-id",
    ACTIVATE: "/api/admin/topic/activate",
    DEACTIVATE: "/api/admin/topic/deactivate",
    SELECT_BOX: "/api/admin/topic/select-box",
    TREE: "/api/admin/topic/tree",
  },

  CERTIFICATE: {
    SKILL_CREATE: "/api/admin/certificate/create-skill",
    SKILL_PAGINATION: "/api/admin/certificate/skill-pagination",
    SKILL_SELECT_BOX: "/api/admin/certificate/skill-select-box",
    SKILL_UPDATE: "/api/admin/certificate/update-skill",
    SKILL_DEACTIVATE: "/api/admin/certificate/deactivate-skill",
    SKILL_ACTIVATE: "/api/admin/certificate/activate-skill",
    SKILL_DETAIL: "/api/admin/certificate/skill-find-by-id",
    TYPE_CREATE: "/api/admin/certificate/create-type",
    TYPE_PAGINATION: "/api/admin/certificate/type-pagination",
    TYPE_SELECT_BOX: "/api/admin/certificate/type-select-box",
    TYPE_UPDATE: "/api/admin/certificate/update-type",
    TYPE_DEACTIVATE: "/api/admin/certificate/deactivate-type",
    TYPE_ACTIVATE: "/api/admin/certificate/activate-type",
    TYPE_DETAIL: "/api/admin/certificate/type-find-by-id",
    TYPE_FIND_BY_CODE: "/api/admin/certificate/type-find-by-code",
  },

  PASSAGE: {
    PAGINATION: "/api/admin/passage/pagination",
    CREATE: "/api/admin/passage/create",
    UPDATE: "/api/admin/passage/update",
    DETAIL: "/api/admin/passage/find-by-id",
    ACTIVATE: "/api/admin/passage/activate",
    DEACTIVATE: "/api/admin/passage/deactivate",
  },

  QUESTION: {
    PAGINATION: "/api/admin/question/pagination",
    CREATE: "/api/admin/question/create",
    UPDATE: "/api/admin/question/update",
    DETAIL: "/api/admin/question/find-by-id",
    ACTIVATE: "/api/admin/question/activate",
    DEACTIVATE: "/api/admin/question/deactivate",
  },

  EXAM: {
    TEMPLATE_CREATE: "/api/admin/exam/exam-template/create",
    TEMPLATE_UPDATE: "/api/admin/exam/exam-template/update",
    TEMPLATE_DETAIL: "/api/admin/exam/exam-template/find-by-id",
    TEMPLATE_PAGINATION: "/api/admin/exam/exam-template/pagination",
    TEMPLATE_PUBLISH: "/api/admin/exam/exam-template/publish",
    TEMPLATE_UNPUBLISH: "/api/admin/exam/exam-template/unpublish",
    TEMPLATE_DEACTIVATE: "/api/admin/exam/exam-template/deactivate",
    TEMPLATE_ACTIVATE: "/api/admin/exam/exam-template/activate",
    PART_CREATE: "/api/admin/exam/exam-part/create",
    PART_UPDATE: "/api/admin/exam/exam-part/update",
    PART_DETAIL: "/api/admin/exam/exam-part/find-by-id",
    PART_PAGINATION: "/api/admin/exam/exam-part/pagination",
    PART_DEACTIVATE: "/api/admin/exam/exam-part/deactivate",
    PART_ACTIVATE: "/api/admin/exam/exam-part/activate",
    GROUP_CREATE: "/api/admin/exam/exam-question-group/create",
    GROUP_UPDATE: "/api/admin/exam/exam-question-group/update",
    GROUP_DETAIL: "/api/admin/exam/exam-question-group/find-by-id",
    GROUP_PAGINATION: "/api/admin/exam/exam-question-group/pagination",
    GROUP_DELETE: "/api/admin/exam/exam-question-group/delete",
    QUESTION_CREATE: "/api/admin/exam/exam-question/create",
    QUESTION_UPDATE: "/api/admin/exam/exam-question/update",
    QUESTION_DETAIL: "/api/admin/exam/exam-question/find-by-id",
    QUESTION_FIND_BY_GROUP: "/api/admin/exam/exam-question/find-by-group",
    QUESTION_PAGINATION: "/api/admin/exam/exam-question/pagination",
    QUESTION_DELETE: "/api/admin/exam/exam-question/delete",
    SESSION_DETAIL: "/api/admin/exam/exam-session/find-by-id",
    SESSION_PAGINATION: "/api/admin/exam/exam-session/pagination",
  },

  PRACTICE_SET: {
    PAGINATION: "/api/admin/practice-set/pagination",
    CREATE: "/api/admin/practice-set/create",
    UPDATE: "/api/admin/practice-set/update",
    DETAIL: "/api/admin/practice-set/find-by-id",
    ACTIVATE: "/api/admin/practice-set/activate",
    DEACTIVATE: "/api/admin/practice-set/deactivate",
    QUESTIONS: "/api/admin/practice-set/questions",
  },

  ARENA: {
    PAGINATION: "/api/admin/arena/pagination",
    CREATE: "/api/admin/arena/create",
    UPDATE: "/api/admin/arena/update",
    DETAIL: "/api/admin/arena/find-by-id",
    ACTIVATE: "/api/admin/arena/activate",
    DEACTIVATE: "/api/admin/arena/deactivate",
  },

  ACHIEVEMENT: {
    PAGINATION: "/api/admin/achievement/pagination",
    CREATE: "/api/admin/achievement/create",
    UPDATE: "/api/admin/achievement/update",
    DETAIL: "/api/admin/achievement/find-by-id",
    ACTIVATE: "/api/admin/achievement/activate",
    DEACTIVATE: "/api/admin/achievement/deactivate",
  },

  AI_GRADING: {
    PAGINATION: "/api/admin/ai-grading-job/pagination",
    CREATE: "/api/admin/ai-grading-job/create",
    DETAIL: "/api/admin/ai-grading-job/find-by-id",
    FIND_LOG_BY_JOB: "/api/admin/ai-grading-job/find-log-by-job",
  },

  ORDER: {
    PAGINATION: "/api/admin/order/pagination",
    CREATE: "/api/admin/order/create",
    DETAIL: "/api/admin/order/find-by-id",
    UPDATE_STATUS: "/api/admin/order/update-status",
  },

  VISITOR: {
    TOTAL_VISITORS: "/api/admin/visitor/total-visitors",
  },
};
